//! Bit-exact Rust port of webapp/chain/acts.mjs: the per-act structural and
//! payload commitments, and the parseMentions resolver both copies of the JS
//! (social/replay.cjs and server.mjs) mirror.
//!
//! Correctness is defined by tests/vectors.json — generated by
//! backend/parity/gen-vectors.mjs from the REAL engine bundle and the live
//! act log, never by this file alone.

use ender_canonical::{hash_canonical, CanonicalError};
use serde_json::{Map, Value};
use std::collections::{HashMap, HashSet};

/// acts.mjs SEED_HANDLES: the four seed-world actors, mentionable before any
/// register act. Order matters: slug collisions resolve last-wins in
/// JS for-in order, which for these keys is insertion order.
pub const SEED_HANDLES: [(&str, &str); 4] =
    [("alice", "Alice"), ("bob", "Bob"), ("carol", "Carol"), ("dave", "Dave")];

const PAYLOAD_FIELDS: [&str; 3] = ["text", "media", "place"];

/// A JS-object-shaped handle table: insertion-ordered, updates in place.
/// (JS for-in visits integer-like keys first; live ids never are, and the
/// parity vectors over the real log hold that assumption down.)
#[derive(Debug, Clone, Default)]
pub struct Handles(Vec<(String, String)>);

impl Handles {
    pub fn seed() -> Self {
        Handles(SEED_HANDLES.iter().map(|(i, h)| (i.to_string(), h.to_string())).collect())
    }

    pub fn from_pairs(pairs: Vec<(String, String)>) -> Self {
        let mut h = Handles::default();
        for (id, handle) in pairs {
            h.set(&id, &handle);
        }
        h
    }

    /// `handles[id] = handle` — JS keeps the original insertion position on
    /// re-assignment, so an id that registers again keeps its slot.
    pub fn set(&mut self, id: &str, handle: &str) {
        match self.0.iter_mut().find(|(i, _)| i == id) {
            Some(entry) => entry.1 = handle.to_string(),
            None => self.0.push((id.to_string(), handle.to_string())),
        }
    }

    fn iter(&self) -> impl Iterator<Item = (&str, &str)> {
        self.0.iter().map(|(i, h)| (i.as_str(), h.as_str()))
    }
}

/// `.toLowerCase().replace(/[^a-z0-9]/g, '')` — both JS copies and this one
/// must resolve identically.
fn slugify(s: &str) -> String {
    s.to_lowercase()
        .chars()
        .filter(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
        .collect()
}

fn is_word_byte(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

/// replay.cjs parseMentions: scan `@([a-zA-Z0-9_]{1,16})` matches in order,
/// resolve each token's slug against the handle table, dedupe on the
/// resolved id, stop at three resolved mentions. Unknown or duplicate
/// tokens never count toward the cap.
pub fn parse_mentions(text: &str, handles: &Handles) -> Vec<String> {
    let mut slug_to_id: HashMap<String, &str> = HashMap::new();
    for (id, handle) in handles.iter() {
        slug_to_id.insert(slugify(handle), id);
    }
    let bytes = text.as_bytes();
    let mut out: Vec<String> = Vec::new();
    let mut seen: HashSet<&str> = HashSet::new();
    let mut i = 0;
    while i < bytes.len() && out.len() < 3 {
        if bytes[i] == b'@' {
            let start = i + 1;
            let mut end = start;
            while end < bytes.len() && end - start < 16 && is_word_byte(bytes[end]) {
                end += 1;
            }
            if end > start {
                // The class is pure ASCII, so byte slicing stays on char
                // boundaries — a multi-byte char simply ends the token,
                // exactly as the JS regex sees it.
                if let Some(&id) = slug_to_id.get(&slugify(&text[start..end])) {
                    if seen.insert(id) {
                        out.push(id.to_string());
                    }
                }
                i = end;
                continue;
            }
        }
        i += 1;
    }
    out
}

const MENTION_KINDS: [&str; 2] = ["post", "event"];

/// acts.mjs structuralProjection: the act minus {text, media, place,
/// redacted}, with `rmen` materialised for posts and events by exactly the
/// computation redaction itself performs. Invariant under lawful redaction.
pub fn structural_projection(act: &Map<String, Value>, handles: &Handles) -> Map<String, Value> {
    let mut s = act.clone();
    for f in PAYLOAD_FIELDS {
        s.remove(f);
    }
    s.remove("redacted");
    let t = act.get("t").and_then(Value::as_str).unwrap_or("");
    if MENTION_KINDS.contains(&t) {
        let rmen = match act.get("rmen") {
            Some(v) => v.clone(),
            None => {
                let text = act.get("text").and_then(Value::as_str).unwrap_or("");
                Value::Array(parse_mentions(text, handles).into_iter().map(Value::String).collect())
            }
        };
        s.insert("rmen".to_string(), rmen);
    }
    s
}

/// acts.mjs payloadProjection: {text, media, place} as they stand, absent
/// fields pinned to null.
pub fn payload_projection(act: &Map<String, Value>) -> Map<String, Value> {
    let mut p = Map::new();
    for f in PAYLOAD_FIELDS {
        p.insert(f.to_string(), act.get(f).cloned().unwrap_or(Value::Null));
    }
    p
}

pub struct Commitments {
    pub structural: Vec<String>,
    pub payload: Vec<String>,
}

/// acts.mjs actCommitments: one walk over the FILE acts (the in-memory
/// seed-world act is not a line and is not hashed). The handle table grows
/// as registers pass; an act's mentions resolve against the table as it
/// stood BEFORE that act.
pub fn act_commitments(file_acts: &[Value]) -> Result<Commitments, CanonicalError> {
    let mut handles = Handles::seed();
    let mut structural = Vec::with_capacity(file_acts.len());
    let mut payload = Vec::with_capacity(file_acts.len());
    for act in file_acts {
        let map = act.as_object().ok_or(CanonicalError::NotAnObject)?;
        structural.push(hash_canonical(&Value::Object(structural_projection(map, &handles)))?);
        payload.push(hash_canonical(&Value::Object(payload_projection(map)))?);
        if map.get("t").and_then(Value::as_str) == Some("register") {
            if let Some(id) = map.get("id").and_then(Value::as_str) {
                if !id.is_empty() {
                    let handle = map.get("handle").and_then(Value::as_str).unwrap_or("");
                    handles.set(id, handle);
                }
            }
        }
    }
    Ok(Commitments { structural, payload })
}

/// acts.mjs payloadMayDiffer: a sealed payload commitment may differ from
/// the current bytes only under the redaction stamp.
pub fn payload_may_differ(act: &Value) -> bool {
    act.get("redacted") == Some(&Value::Bool(true))
}

/// chain.mjs findEpochCloses.
pub fn find_epoch_closes(file_acts: &[Value]) -> Vec<(usize, i64)> {
    file_acts
        .iter()
        .enumerate()
        .filter(|(_, a)| a.get("t").and_then(Value::as_str) == Some("closeEpoch"))
        .map(|(i, a)| (i, a.get("epoch").and_then(Value::as_i64).unwrap_or(-1)))
        .collect()
}

#[derive(Debug)]
pub struct BlockEntry {
    pub height: u64,
    pub epoch: i64,
    pub ok: bool,
    pub notes: Vec<String>,
    pub tombstoned: u64,
    pub hash: String,
}

#[derive(Debug)]
pub struct VerifyReport {
    pub ok: bool,
    pub height: usize,
    pub blocks: Vec<BlockEntry>,
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
    pub tombstoned: u64,
}

/// chain.mjs verifyChain minus the epoch-package replay comparison: cheap
/// structural verification only. See [`verify_chain`] for the full check.
pub fn verify_chain_structure(
    file_acts: &[Value],
    blocks: &[Value],
    pinned_producer: Option<&str>,
) -> Result<VerifyReport, CanonicalError> {
    verify_chain_inner(file_acts, blocks, pinned_producer, None)
}

/// The COMPLETE chain.mjs verifyChain: everything structural plus the
/// epoch-package replay — each block's prefix is replayed through
/// ender-engine and the recomputed package's canonical bytes must equal the
/// sealed ones. On mismatch, `editions` (the current engine/replay source
/// hashes) attributes the difference: sealed under different editions is a
/// warning, same editions is a fault.
pub fn verify_chain(
    file_acts: &[Value],
    blocks: &[Value],
    pinned_producer: Option<&str>,
    editions: Option<(&str, &str)>,
) -> Result<VerifyReport, CanonicalError> {
    verify_chain_inner(file_acts, blocks, pinned_producer, Some(editions))
}

/// Where the JS would crash on a malformed block (missing range/package),
/// this reports a fault instead. `replay_editions`: None = skip the replay
/// check; Some(editions) = run it with optional drift attribution.
fn verify_chain_inner(
    file_acts: &[Value],
    blocks: &[Value],
    pinned_producer: Option<&str>,
    replay_editions: Option<Option<(&str, &str)>>,
) -> Result<VerifyReport, CanonicalError> {
    use ender_canonical::{block_hash, verify_block_signature, CHAIN_VERSION, NET_ID};

    let mut report = VerifyReport {
        ok: true,
        height: blocks.len(),
        blocks: Vec::new(),
        errors: Vec::new(),
        warnings: Vec::new(),
        tombstoned: 0,
    };

    let closes = find_epoch_closes(file_acts);
    let Commitments { structural, payload } = act_commitments(file_acts)?;

    if blocks.len() > closes.len() {
        report.ok = false;
        report.errors.push(format!(
            "chain has {} blocks but the log closes only {} epochs",
            blocks.len(),
            closes.len()
        ));
        return Ok(report);
    }
    if blocks.len() < closes.len() {
        report.warnings.push(format!(
            "log has {} closed epoch(s) not yet sealed",
            closes.len() - blocks.len()
        ));
    }

    let mut prev: Option<String> = None;
    let mut producers: HashSet<String> = HashSet::new();

    for (n, b) in blocks.iter().enumerate() {
        let epoch = b.get("epoch").and_then(Value::as_i64).unwrap_or(-1);
        let mut entry = BlockEntry {
            height: (n + 1) as u64,
            epoch,
            ok: true,
            notes: Vec::new(),
            tombstoned: 0,
            hash: String::new(),
        };
        macro_rules! bad {
            ($($arg:tt)*) => {{
                let msg = format!($($arg)*);
                entry.ok = false;
                entry.notes.push(msg.clone());
                report.ok = false;
                report.errors.push(format!("block {}: {}", n + 1, msg));
            }};
        }

        let v_ok = b.get("v").and_then(Value::as_u64) == Some(CHAIN_VERSION);
        let net_ok = b.get("net").and_then(Value::as_str) == Some(NET_ID);
        if !v_ok || !net_ok {
            bad!("unknown version/net");
        }
        if b.get("height").and_then(Value::as_u64) != Some((n + 1) as u64) {
            bad!("height mismatch, expected {}", n + 1);
        }
        let link_ok = match (b.get("prev"), &prev) {
            (Some(Value::Null), None) | (None, None) => true,
            (Some(Value::String(s)), Some(p)) => s == p,
            _ => false,
        };
        if !link_ok {
            bad!("broken hash link to previous block");
        }

        let start = if n == 0 { 0 } else { closes[n - 1].0 + 1 };
        let end = closes[n].0;
        let b_start = b.pointer("/range/start").and_then(Value::as_u64);
        let b_end = b.pointer("/range/end").and_then(Value::as_u64);
        if b_start != Some(start as u64) || b_end != Some(end as u64) {
            bad!("range does not match the log's epoch boundaries {start}-{end}");
        } else {
            let b_acts = b.get("acts").and_then(Value::as_array);
            for i in 0..=(end - start) {
                let sealed = b_acts.and_then(|a| a.get(i)).and_then(Value::as_str);
                if sealed != Some(structural[start + i].as_str()) {
                    bad!("act {}: structural hash mismatch — the record itself differs", start + i);
                    break;
                }
            }
            let b_payloads = b.get("payloads").and_then(Value::as_array);
            let mut tomb = 0u64;
            for i in 0..=(end - start) {
                let sealed = b_payloads.and_then(|a| a.get(i)).and_then(Value::as_str);
                if sealed != Some(payload[start + i].as_str()) {
                    if payload_may_differ(&file_acts[start + i]) {
                        tomb += 1;
                    } else {
                        bad!("act {}: payload differs from its sealed commitment with no redaction stamp", start + i);
                        break;
                    }
                }
            }
            entry.tombstoned = tomb;
            report.tombstoned += tomb;
        }

        for (field, root_field) in [("acts", "actsRoot"), ("payloads", "payloadsRoot")] {
            let leaves: Option<Vec<String>> = b.get(field).and_then(Value::as_array).map(|a| {
                a.iter().map(|v| v.as_str().unwrap_or_default().to_string()).collect()
            });
            let sealed_root = b.get(root_field).and_then(Value::as_str);
            match leaves {
                Some(l) if Some(ender_canonical::merkle_root(&l).as_str()) == sealed_root => {}
                _ => bad!("{root_field} does not match its own leaf list"),
            }
        }

        match b.get("package") {
            Some(pkg) => {
                if hash_canonical(pkg).ok().as_deref() != b.get("stateRoot").and_then(Value::as_str) {
                    bad!("stateRoot does not hash its own package");
                }
            }
            None => bad!("block carries no package"),
        }

        // chain.mjs 201-221: replay the prefix and compare the recomputed
        // epoch package byte-for-byte, attributing any difference.
        if let Some(editions) = replay_editions {
            if entry.ok {
                let mut prefix: Vec<Value> = Vec::with_capacity(end + 2);
                prefix.push(serde_json::json!({ "t": "seedWorld" }));
                prefix.extend_from_slice(&file_acts[..=end]);
                let st = ender_engine::replay(&prefix);
                let epoch_f = b.get("epoch").and_then(Value::as_f64).unwrap_or(f64::NAN);
                match ender_engine::package::epoch_package(&st, epoch_f) {
                    Err(e) => bad!("replay does not close epoch {} here: {}", entry.epoch, e),
                    Ok(pkg) => {
                        let replayed = ender_canonical::canonical(&pkg)?;
                        let sealed = b
                            .get("package")
                            .map(ender_canonical::canonical)
                            .transpose()?;
                        if sealed.as_ref() != Some(&replayed) {
                            let drift = editions.map_or(false, |(eng, rep)| {
                                b.pointer("/editions/engine").and_then(Value::as_str) != Some(eng)
                                    || b.pointer("/editions/replay").and_then(Value::as_str)
                                        != Some(rep)
                            });
                            if drift {
                                entry.notes.push(
                                    "state package differs — ATTRIBUTED to formula-edition drift (sealed under different engine/replay source)"
                                        .to_string(),
                                );
                                report.warnings.push(format!(
                                    "block {}: sealed under a different formula edition; state not reproducible with current code",
                                    n + 1
                                ));
                            } else {
                                bad!("state package does not replay: same formula editions, different result");
                            }
                        }
                    }
                }
            }
        }

        if !verify_block_signature(b) {
            bad!("signature does not verify against the named producer");
        }
        if let Some(p) = b.get("producer").and_then(Value::as_str) {
            producers.insert(p.to_string());
            if let Some(pin) = pinned_producer {
                if p != pin {
                    bad!("producer is not the pinned key");
                }
            }
        }

        let hash = block_hash(b)?;
        prev = Some(hash.clone());
        entry.hash = hash;
        report.blocks.push(entry);
    }
    if producers.len() > 1 {
        report.warnings.push(format!(
            "more than one producer key appears in this chain ({})",
            producers.len()
        ));
    }
    Ok(report)
}
